### ISSUE TITLE
Release on Firefox Addons

### ISSUE THREAD

**Issue by 2zqa** [Elizaveta239/sort-the-meet#4]
As it seems this extension already supports Firefox. It would be great to support Firefox by uploading it to the [Firefox Addons](https://addons.mozilla.org/). Instructions can be found here: https://extensionworkshop.com/documentation/publish/submitting-an-add-on/

I would also be willing to upload and manage it myself if you'd prefer, of course with giving due credits.

**Comment by Elizaveta239** [comment]
Hi! Yes, I don't think I'll find time for that on my own, so feel free to publish this code for Firefox as well! It would be really great to have this extension for Firefox! :)

**Comment by 2zqa** [comment]
~~Thanks! I'll do this when #5 is merged.~~

I've submitted the addon from my own fork for now. It's still under review, but should become available if it survives the review: https://addons.mozilla.org/nl/firefox/addon/sort-the-meet/

Update: it's available! 🎉
